DROP TABLE IF EXISTS note;
DROP TABLE IF EXISTS toc;

CREATE TABLE note (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  created TIMESTAMP NOT NULL,
  updated TIMESTAMP NOT NULL,
  content TEXT NOT NULL,
  imported TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX titles ON note(title);

CREATE TABLE toc (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    guid TEXT NOT NULL,
    title TEXT NOT NULL
);

CREATE INDEX guids ON toc(guid);